---
abstract: 'Show timezone offset strings like +0900'
author:
  - '-2014 Piotr Roszatycki <dexter@cpan.org>.'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.14.1, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-TZOffset
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Time::TZOffset:
    file: lib/Time/TZOffset.pm
    version: 0.03
requires:
  perl: 5.008004
resources:
  bugtracker: https://github.com/kazeburo/Time-TZOffset/issues
  homepage: https://github.com/kazeburo/Time-TZOffset
  repository: git://github.com/kazeburo/Time-TZOffset.git
version: 0.03
x_contributors:
  - 'Jacques Germishuys <jacquesg@striata.com>'
  - 'Masahiro Nagano <kazeburo@gmail.com>'
